/*
 The pipeline is made up of 6 main steps
    1. Git clone and setup
    2. Build and local tests
    3. Publish Docker and Helm
    4. Deploy to dev and test
    5. Deploy to staging and test
    6. Optionally deploy to production and test
 */

def coreServerTag = "agao2/core_server:${env.tag}"
def coreServerTag = "agao2/web_app:${env.tag}"

pipeline {
    agent { node { label 'master' } }  // just use master node i guess

    stages {

        stage('Checkout') {
            echo "grabbing code from repository"
            git branch: "master", url: 'https://git.jfrog.info/scm/~eldada/acme-ci-cd.git'
            
            // Validate kubectl
            sh "kubectl cluster-info"
        }
    }
}
