def coreServerTag = "agao2/core_server:${env.tag}"
def webAppTag = "agao2/web_app:${env.tag}"


pipeline {
    agent { node { label 'master' } }  // just use master i guess

 stages {
        stage('Git clone') {
            steps {
                echo "grabbing code from repository"
                git branch: "master", url: 'https://github.com/agao2/Downvoot.git'
            }
        }
        stage('Build and push image')
        {
            steps
            {
                // assume docker server is accessible and we're pushing to right registry 
                sh "docker build -t ${coreServerTag} -f ../core_server/prod.Dockerfile ."
                sh "docker push ${coreServerTag}"
                sh "docker build -t ${webAppTag} -f ../web_app/prod.Dockerfile ."
                sh "docker-push ${webAppTag}"
            }
        }
        stage ('Deploy')
        {
            steps 
            {
                sh 'kubectl apply -f ../kubernetes/'
            }
        }
    }
}

